lockss-spring version 2.12.0

diff --git a/lockss-spring/docker/bin/docker-entrypoint b/lockss-spring/docker/bin/docker-entrypoint
--- a/lockss-spring/docker/bin/docker-entrypoint
+++ b/lockss-spring/docker/bin/docker-entrypoint
@@ -1,6 +1,6 @@
 #!/bin/sh
 
-# Copyright (c) 2000-2023, Board of Trustees of Leland Stanford Jr. University
+# Copyright (c) 2000-2026, Board of Trustees of Leland Stanford Jr. University
 #
 # Redistribution and use in source and binary forms, with or without
 # modification, are permitted provided that the following conditions are met:
@@ -65,11 +65,14 @@ Apply_Config()
     && ( cd "${TMP}" && tar cf - --exclude '*.tpl' . ) | tar xf -
     RET=$?
     rm -rf "${TMP}"
-    echo "Done applying config from ${1}."
-    return $RET
+    if [ $RET -eq 0 ] ; then
+      echo "Done applying config from ${1}."
+    else
+      echo "${_0}: error applying config from ${1}: ${RET}"
+      Exit 1
+    fi
   else
     echo "No config directory ${1}."
-    return 0
   fi
 }
 
@@ -103,7 +106,7 @@ Check_Dir_Read()
 
 Check_Executable()
 {
-  if ! which "${1}" > /dev/null 2>&1 ; then
+  if ! command -v "${1}" > /dev/null ; then
     echo "${_0}: PATH executable not found: ${1}"
     Exit 1
   fi
@@ -283,7 +286,7 @@ Check_Set "${LOCKSS_TMP}" LOCKSS_TMP
 # Layer configuration
 
 echo "Layering configuration..."
-mkdir -p "${LOCKSS_HOME}/etc"
+mkdir -p "${LOCKSS_HOME}/etc" || Exit 1
 Apply_Config "${LOCKSS_HOME}/etc.base"
 echo "Done layering configuration."
 
@@ -299,14 +302,17 @@ JVM_OPTS_THIS_SERVICE=''
 ARGS_THIS_SERVICE=''
 
 if [ "${LOCKSS_IS_REPO}" = 'true' ]; then
-  Check_File "${SECRETS}/solr-auth"
 
   #
   # LOCKSS_IS_REPO
   #
   echo "Repository service configuration..."
-  ARGS_THIS_SERVICE="--spring.config.location=classpath:/application.properties,file:${CONFIGS}/lockss.properties -s solr:${SECRETS}/solr-auth"
+  ARGS_THIS_SERVICE="--spring.config.location=classpath:/application.properties,file:${CONFIGS}/lockss.properties"
 
+  if [ "${USE_SOLR_INDEX}" = 'true' ]; then
+    Check_File "${SECRETS}/solr-auth"
+    ARGS_THIS_SERVICE="${ARGS_THIS_SERVICE} -s solr:${SECRETS}/solr-auth"
+  fi
 fi
 
 if [ "${LOCKSS_IS_POLLER}" = 'true' ]; then
