Version 2.0. All operations now have a parent wrapper. Upgrade operation. Rename *-impl to *-native. ONBUILD directives to check required file names. Depend on only awk and which. Cosmetic.

diff --git a/lockss-ipm/docker/ipm/bin/install-essential-packages b/lockss-ipm/docker/ipm/bin/install-essential-packages
--- a/lockss-ipm/docker/ipm/bin/install-essential-packages
+++ b/lockss-ipm/docker/ipm/bin/install-essential-packages
@@ -29,14 +29,34 @@
 # ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 # POSSIBILITY OF SUCH DAMAGE.
 
-IPM='ipm-install'
-if [ "X${1}" = "X--uninstall" ]; then
-  IPM='ipm-uninstall'
+# Notes:
+#
+# which is not pre-installed in centos:7.6.1810
+#
+# All others are pre-installed in alpine:3.9, centos:7.6.1810,
+# ubuntu:xenial-20190122
+
+_0="$(basename "${0}")"
+
+IPKGS='awk coreutils findutils grep netcat sed which'
+
+ARG="${1}"
+
+if [ "${ARG}" = "--help" ]; then
+  echo "Usage: ${_0} [--uninstall]"
+  echo "Usage: ${_0} --help"
+  echo "Installs packages without which a base image is unlikely to run"
+  echo "Examples: ${IPKGS}"
+  exit 0
 fi
 
-$IPM curl \
-     dnsutils \
-     gzip \
-     less \
-     ping \
-     tar
+if [ $# -eq 0 ]; then
+  IPM='ipm-install'
+elif [ "${ARG}" = "--uninstall" ]; then
+  IPM='ipm-uninstall'
+else
+  echo "${_0}: invalid argument: ${ARG}" >&2
+  exit 1
+fi
+
+$IPM $IPKGS
diff --git a/lockss-ipm/docker/ipm/bin/install-useful-packages b/lockss-ipm/docker/ipm/bin/install-useful-packages
--- a/lockss-ipm/docker/ipm/bin/install-useful-packages
+++ b/lockss-ipm/docker/ipm/bin/install-useful-packages
@@ -33,29 +33,23 @@ _0="$(basename "${0}")"
 
 ARG="${1}"
 
+IPKGS='curl dnsutils gzip less ping tar'
+
 if [ "${ARG}" = "--help" ]; then
-  echo "Usage: ${_0}"
-  echo "Installs one ore more idealized packages"
+  echo "Usage: ${_0} [--uninstall]"
+  echo "Usage: ${_0} --help"
+  echo "Installs packages not essential at runtime but useful for human intervention"
+  echo "Examples: ${IPKGS}"
   exit 0
 fi
 
 if [ $# -eq 0 ]; then
-  echo "${_0}: expected at least one argument" >&2
+  IPM='ipm-install'
+elif [ "${ARG}" = "--uninstall" ]; then
+  IPM='ipm-uninstall'
+else
+  echo "${_0}: invalid argument: ${ARG}" >&2
   exit 1
 fi
 
-if ! which ipm-install-native > /dev/null 2>&1 ; then
-  echo "${_0}: ipm-install-native is not on the PATH" >&2
-  exit 1
-fi
-
-NPKGS=''
-for ipkg in "$@" ; do
-  if [ "$(ipm-check "${ipkg}")" = 'false' ]; then
-    NPKGS="${NPKGS} $(ipm-translate "${ipkg}")"
-  fi
-done
-
-ipm-update
-ipm-install-native ${NPKGS}
-ipm-clean
+$IPM $IPKGS
diff --git a/lockss-ipm/docker/ipm/bin/ipm-setup b/lockss-ipm/docker/ipm/bin/ipm-setup
--- a/lockss-ipm/docker/ipm/bin/ipm-setup
+++ b/lockss-ipm/docker/ipm/bin/ipm-setup
@@ -29,7 +29,6 @@
 # ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 # POSSIBILITY OF SUCH DAMAGE.
 
-
 _0="$(basename "${0}")"
 
 ARG="${1}"
@@ -37,18 +36,30 @@ PKGS='/usr/local/etc/ipm/ipm-packages.txt'
 ORIG='/usr/local/etc/ipm/ipm-originally.txt'
 
 if [ "${ARG}" = "--help" ]; then
-  echo "Usage: ${_0}"
+  echo "Usage: ${_0} [NPKG...]"
+  echo "       ${_0} --help"
   echo "Writes a baseline of installed packages to ${ORIG}"
+  echo "Calls ipm-update, ipm-upgrade, install-essential-packages"
+  echo "Optionally installs the given native packages with ipm-install-native"
+  echo "Finally calls ipm-clean"
   exit 0
 fi
 
 if [ ! -f "${PKGS}" ]; then
-  echo "${_0}: ${PKGS} not found"
+  echo "${_0}: ${PKGS} not found" >&2
   exit 1
 fi
 
-for ipkg in $(cut -s -f1 "${PKGS}"); do
-  if [ "$(ipm-check "${ipkg}")" = "true" ]; then
-    echo "${ipkg}"
-  fi
-done > "${ORIG}"
+: \
+&& for ipkg in $(awk -F"\t" '{print $1}' "${PKGS}"); do
+     if [ "$(ipm-check "${ipkg}")" = "true" ]; then
+       echo "${ipkg}"
+     fi
+   done > "${ORIG}" \
+&& ipm-update \
+&& ipm-upgrade \
+&& install-essential-packages \
+&& if [ $# -gt 0 ]; then
+     ipm-install-native "$@"
+   fi \
+&& ipm-clean
