Map from one idealized package to one or more system packages. Bug fixes. Documentation. Help messages. Versioning. Build scripts.

diff --git a/lockss-ipm/docker/ipm/bin/ipm-originally b/lockss-ipm/docker/ipm/bin/ipm-originally
--- a/lockss-ipm/docker/ipm/bin/ipm-originally
+++ b/lockss-ipm/docker/ipm/bin/ipm-originally
@@ -29,19 +29,24 @@
 # ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 # POSSIBILITY OF SUCH DAMAGE.
 
-IPM='ipm-install'
-if [ "X${1}" = 'X--uninstall' ]; then
-  IPM='ipm-uninstall'
+_0="$(basename "${0}")"
+ARG="${1}"
+ORIG='/usr/local/etc/ipm/ipm-originally.txt'
+
+if [ "${ARG}" = "--help" ]; then
+  echo "Usage: ${_0} IPKG"
+  echo "Prints true if the idealized package was originally installed, false otherwise"
+  exit 0
 fi
 
-$IPM bash \
-     file \
-     findutils \
-     lynx \
-     netcat \
-     openssh-client \
-     rsync \
-     tcpdump \
-     traceroute \
-     unzip \
-     zip
+if [ "$#" != "1" ]; then
+  echo "${_0}: expected exactly one argument but got $#" >&2
+  exit 1
+fi
+
+if [ ! -f "${ORIG}" ]; then
+  echo "${_0}: ${ORIG} not found; run ipm-setup" >&2
+  exit 1
+fi
+
+grep -q -x "${ARG}" "${ORIG}" && echo 'true' || echo 'false'
diff --git a/lockss-ipm/docker/ipm/bin/ipm-setup b/lockss-ipm/docker/ipm/bin/ipm-setup
--- a/lockss-ipm/docker/ipm/bin/ipm-setup
+++ b/lockss-ipm/docker/ipm/bin/ipm-setup
@@ -29,15 +29,26 @@
 # ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 # POSSIBILITY OF SUCH DAMAGE.
 
-sort /etc/ipm/ipm-packages.txt | while read l; do
-  ipkg=$(echo "${l}" | cut -f1)
-  desc=$(echo "${l}" | cut -f2)
-  if $(grep -q -x "${ipkg}" /etc/ipm/ipm-originally.txt); then
-    inst='a'
-  elif [ "$(ipm-check "${ipkg}")" = "true" ]; then
-    inst='y'
-  else
-    inst='n'
+
+_0="$(basename "${0}")"
+
+ARG="${1}"
+PKGS='/usr/local/etc/ipm/ipm-packages.txt'
+ORIG='/usr/local/etc/ipm/ipm-originally.txt'
+
+if [ "${ARG}" = "--help" ]; then
+  echo "Usage: ${_0}"
+  echo "Writes a baseline of installed packages to ${ORIG}"
+  exit 0
+fi
+
+if [ ! -f "${PKGS}" ]; then
+  echo "${_0}: ${PKGS} not found"
+  exit 1
+fi
+
+for ipkg in $(cut -s -f1 "${PKGS}"); do
+  if [ "$(ipm-check "${ipkg}")" = "true" ]; then
+    echo "${ipkg}"
   fi
-  printf '%.1s %-14s %-60s\n' "${inst}" "${ipkg}" "${desc}"
-done
+done > "${ORIG}"
